### ISSUE TITLE
False status when retrieving policy details in MemDef, ScriptControl and Optics

### ISSUE THREAD

**Issue by Boerner1337** [jan-tee/TietzeIO.CyShell#3]
When retrieving policies via 

**> Get-CylancePolicies | Get-CylancePolicy**

 the output shows in any case that ScriptControl, MemDef as well as OPTICS are disabled. This is also the case for policies where it is actually enabled. The output should then show "true" instead of "false". 

Example:

![issue1](https://user-images.githubusercontent.com/31093777/62147003-df537b80-b2f6-11e9-8533-c2dcc95f8ac0.png)

**Comment by jan-tee** [comment]
Very much fixed in 1.0.8, which was released a moment ago
